name: PHPStan lint

on:
  pull_request:
    branches:
      - master
      - develop
      - branch-*

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']

    name: WPRocket lint with PHPStan. PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v1

	 name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-scripts

    # Linting
    - name: Lint with phpstan
      run: |
        composer run-stan
